config/routes.rb
ChessCamp::Application.routes.draw do
  resources :reports

  get "students/edit"
  get "students/index"
  get "students/new"
  get "students/show"
  get "families/edit"
  get "families/index"
  get "families/new"
  get "families/show"
  get "locations/edit"
  get "locations/new"
  get "locations/index"
  get "locations/show"
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps 
  resources :users
  resources :sessions
  resources :locations
  resources :families
  resources :students
  # semi-static routes
  get 'report/year/:year', to: 'report#yearly', as: :yearly
  get 'report/:id', to: 'report#generate', as: :helper
  get 'report/family/:id', to: 'report#family_report', as: :family_report
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/payment_report', to: 'home#payment_report', as: :payment_report
  get 'home/payment_report13', to: 'home#payment_report13', as: :payment_report13
  get 'home/payment_report15', to: 'home#payment_report15', as: :payment_report15
  #get 'home/payment_report/:year', to: 'home#payment_report', as: :payment_report
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # set the root url
  root to: 'home#index'

end

app/controllers/camps_controller.rb
class CampsController < ApplicationController

  require 'will_paginate/array'
  before_action :set_camp, only: [:show, :edit, :update, :destroy, :camp_payment]
  before_action :check_login, only: [:new, :edit, :update, :destroy]
  authorize_resource 

  def index
    @upcoming_camps = Camp.upcoming.active.chronological
    @possible_to_see_upcoming_camps = @upcoming_camps.select{|c| (can? :read, c)}.paginate(:page => params[:page], :per_page => 10)

    @upcoming_camps = @possible_to_see_upcoming_camps


    @past_camps = Camp.past.chronological.paginate(:page => params[:page]).per_page(10)
    @inactive_camps = Camp.inactive.alphabetical.to_a
  end

  def show
    @instructors = @camp.instructors.alphabetical.to_a
    #@curriculums = Curriculum.all.map{|c| if c.camp_id }
    @students = @camp.students.all.map{|s| s}
  end

  def new
    @camp = Camp.new
  end

  def edit
  end

  def create
    @camp = Camp.new(camp_params)
    if @camp.save
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @camp.update(camp_params)
      redirect_to @camp, notice: "The camp #{@camp.name} (on #{@camp.start_date.strftime('%m/%d/%y')}) was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @camp.destroy
    redirect_to camps_url, notice: "#{@camp.name} camp on #{@camp.start_date.strftime('%m/%d/%y')} was removed from the system."
  end


  private
    def set_camp
      @camp = Camp.find(params[:id])
    end

    def camp_params
      params.require(:camp).permit(:curriculum_id, :cost, :start_date, :end_date, :time_slot, :max_students, :location_id, :active, :instructor_ids => [], :location_ids => [])
    end
end

app/views/camps/_camp_details.html.erb
<h3>Camp Details</h3><br />
<strong>Name:&nbsp;&nbsp;</strong> 
  <%= link_to @camp.name, curriculum_path(@camp.curriculum) %><br /><br />

<strong>Rating:&nbsp;&nbsp;</strong> 
<%= "#{@camp.curriculum.min_rating} - #{@camp.curriculum.max_rating}" %><br /><br />

<strong>Cost:&nbsp;&nbsp;</strong> 
  <%= number_to_currency(@camp.cost) %><br /><br />

<strong>Max Students:&nbsp;&nbsp;</strong> 
  <%= @camp.max_students %><br /><br />

<strong>Dates:&nbsp;&nbsp;</strong> 
  <%= @camp.start_date.strftime('%m/%d/%y') %> 
  <% if @camp.start_date != @camp.end_date %>
    <%= "- #{@camp.end_date.strftime('%m/%d/%y')}" %>
  <% end %>
  <br /><br />

<strong>Time:&nbsp;&nbsp;</strong> 
  <%= @camp.time_slot == "am" ? "Morning" : "Afternoon" %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @camp.active ? "Yes" : "No" %><br /><br />

<%= link_to "Back to camps", camps_path, class: "button tiny radius" %>&nbsp;&nbsp;
<% if logged_in? %>
  <% if current_user.role == 'admin' %>
<%= link_to "Print Report", helper_path(id: @camp.id), class: "button tiny radius" %>
<%= link_to "Edit this camp", edit_camp_path(@camp), class: "button tiny radius" %>&nbsp;&nbsp;
<%= link_to 'Destroy camp', camp_path(@camp), data: { confirm: 'Are you sure you want to permanently remove this camp from the system?' }, method: :delete, class: "button tiny radius alert" %>
  <% end %>
<% end %>

app/views/camps/_camp_instructors.html.erb
<% unless @instructors.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Camp Instructors</h5>
    <ul class="side-nav">
      <% @instructors.each do |instructor| %>
        <li><%= link_to instructor.name, instructor_path(instructor) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>No Instructors</h5>
  </div>
<% end %>
<% if logged_in? %>
  <% if can? :read, @camp %>
  <div class="panel clearfix">
      <h5>Registrations (<%= "#{@camp.registrations.size}" %>)
     <!--  <h5>Registered Students</h5> -->
      <ul class="side-nav">
        <% @students.each do |s| %>
          <li><%= link_to s.name, student_path(s) %><%= "Student Rating #{s.rating}" %></li>
        <% end %>
      </ul>
  </div>

  <% else %>
    <div class="panel clearfix">
      <h5>No Students</h5>
    </div>
  <% end %>
<% else %>
  <div class="panel clearfix">
      <h5>Pre-registered Students </h5>
      <ul class="side-nav">
        <% @students.each do |s| %>
          <li><%= link_to s.name, student_path(s) %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/camps/_camps.html.erb
<h3><%= status %> Camps</h3>

<table class="table">
  <tr>
    <th width="260">Name</th>
    <th width="120">Start On</th>
    <th width="120">Time</th>
    <th></th>
    <th></th>
  </tr>

<% camps.each do |camp| %>
  <tr>
    <td><%= link_to camp.name, camp_path(camp) %></td>
    <td align="center"><%= camp.start_date.strftime('%m/%d/%y') %></td>
    <td align="center"><%= camp.time_slot == "am" ? "Morning" : "Afternoon" %></td>
    <% if logged_in? %>
      <% if current_user.role == 'admin' %>
    <td><%= link_to 'Edit', edit_camp_path(camp), class: "button tiny radius" %></td>
    <td><%= link_to 'Report', helper_path(camp), class: "button tiny radius" %></td>
      <% end %>
    <% end %>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/camps/_form.html.erb
<%= simple_form_for(@camp, html: { class: 'form-horizontal' }) do |f| %>
       
    <div class="row">
      <div class="small-6 columns">
        <h3><%= controller.action_name.capitalize %> Camp</h3>
        <%= f.input :curriculum_id, collection: Curriculum.active.alphabetical, prompt: "Select curriculum..." %>
        <%= f.input :cost %>
        <%= f.input :max_students %>
        <%= f.input :start_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 1, end_year: Date.today.year + 1 %>
        <%= f.input :end_date, as: :date, order: [:month, :day, :year], include_blank: true, start_year: Date.today.year - 1, end_year: Date.today.year + 1 %>
        <%= f.input :time_slot, collection: [['Morning','am'],['Afternoon','pm']], prompt: "Select time..." %>
        <%= f.collection_select :location_id, Location.active.alphabetical, :id, :name %>
        <%#= f.input :location_id, label: "", collection: Location.active.alphabetical, as: :select_boxes %>
        <%= f.input :active %>
      </div>
      <div class="small-1 columns">&nbsp;</div>
      <div class="small-5 columns">
        <% if controller.action_name=="edit" && @camp.active %>
        <h3>Camp Instructor(s)</h3>
        <%= f.input :instructor_ids, label: "", collection: Instructor.active.alphabetical, as: :check_boxes %>
        <% end %>
      </div>
    </div>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of camps', camps_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/camps/_inactive_camps.html.erb
<% if logged_in? %>
      <% if current_user.role == 'admin' %>
		<% unless @inactive_camps.empty? %>
		  <div class="panel clearfix">
		    <h5>Inactive Camps</h5>
		    <ul class="side-nav">
		      <% @inactive_camps.each do |camp| %>
		        <li><%= link_to camp.name, camp_path(camp) %></li>
		      <% end %>
		    </ul>
		  </div>
		<% end %>
	<% end %>
<% end %>

app/views/camps/edit.html.erb
<div class = "transparent">
<div class="row">
  <div class="small-12 columns">
    <%= render :partial => "form" %>
  </div>
</div>
</div>

app/views/camps/index.html.erb
<div class = "transparent">
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "camps", locals: { status: "Upcoming", camps: @upcoming_camps } %>
    <p>&nbsp;</p>
    <% if logged_in? %>
      <% if @past_camps.nil? %>
        <%= render :partial => "camps", locals: { status: "Past", camps: @past_camps } %>
      <% end %>
    <br />
    <% if logged_in? %>
      <% if current_user.role == 'admin' %>
       <%= link_to "Add a new camp", new_camp_path, class: "button tiny radius" %>
      <% end %>
    <% end %>
    <% end %>
  </div>
  <% if logged_in? %>
  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render :partial => "inactive_camps" %>
  </div>
  <% end %>
</div>
</div>

app/views/camps/new.html.erb
<div class = "transparent">
<div class="row">
  <div class="small-12 columns">
    <%= render :partial => "form" %>
  </div>
</div>
</div>

app/views/camps/show.html.erb
<div class = "transparent">
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "camp_details" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'camp_instructors' %>
  </div>
</div>
</div>