config/routes.rb
ChessCamp::Application.routes.draw do
  resources :reports

  get "students/edit"
  get "students/index"
  get "students/new"
  get "students/show"
  get "families/edit"
  get "families/index"
  get "families/new"
  get "families/show"
  get "locations/edit"
  get "locations/new"
  get "locations/index"
  get "locations/show"
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps 
  resources :users
  resources :sessions
  resources :locations
  resources :families
  resources :students
  # semi-static routes
  get 'report/year/:year', to: 'report#yearly', as: :yearly
  get 'report/:id', to: 'report#generate', as: :helper
  get 'report/family/:id', to: 'report#family_report', as: :family_report
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/payment_report', to: 'home#payment_report', as: :payment_report
  get 'home/payment_report13', to: 'home#payment_report13', as: :payment_report13
  get 'home/payment_report15', to: 'home#payment_report15', as: :payment_report15
  #get 'home/payment_report/:year', to: 'home#payment_report', as: :payment_report
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # set the root url
  root to: 'home#index'

end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  include ActionView::Helpers::NumberHelper
  before_action :set_family, only: [:show, :edit, :update, :destroy]
  before_action :check_login
  authorize_resource 

  def index
    @active_families = Family.active.alphabetical.paginate(:page => params[:page]).per_page(10)
    @inactive_families = Family.inactive.alphabetical.paginate(:page => params[:page]).per_page(10)
  end

  def show
  	@family.phone = number_to_phone(@family.phone)
  	@students = @family.students.to_a
  end

  def new
    @family = Family.new
  end

  def edit
  	@family.phone = number_to_phone(@family.phone)
  end

  def create
    @family = Family.new(family_params)
    if @family.save
      redirect_to @family, notice: "#{@family.family_name} family was added to the system."
    else
      render action: 'new'
    end
  end

  def update
    if @family.update(family_params)
      redirect_to @family, notice: "#{@family.family_name} family was revised in the system."
    else
      render action: 'edit'
    end
  end

  def destroy
    @family.destroy
    redirect_to families_url, notice: "#{@family.family_name} family was removed from the system."
  end

  private
    def set_family
      @family = Family.find(params[:id])
    end

    def family_params
      params.require(:family).permit(:family_name, :parent_first_name, :email, :phone, :active)
    end

end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/views/families/_active_families.html.erb
<h3>Active Families</h3>

<table class="table">
  <tr>
    <th width="200">Family Name</th>
    <th width="200">Parent </th>
    <th width="200">Phone</th>
    <th></th>
    <th></th>
  </tr>

<% @active_families.each do |family| %>
  <tr>
    <td><%= link_to family.family_name, family_path(family) %></td>
    <td align="center"><%= family.parent_first_name %></td>
    <td align="center"><%= number_to_phone(family.phone) %></td>
    <td><%= link_to 'Edit', edit_family_path(family), class: "button tiny radius" %></td>
    <td><%= link_to 'Report', family_report_path(family), class: "button tiny radius" %></td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @active_families, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/families/_family_details.html.erb
<h3>Family Details</h3><br />
<strong>Family Name:&nbsp;&nbsp;</strong> 
  <%= @family.family_name %><br /><br />

<strong>Parent:&nbsp;&nbsp;</strong>
  <%= @family.parent_first_name %><br /><br />

<strong>Email:&nbsp;&nbsp;</strong> 
 <%= @family.email %><br /><br />

<strong>Phone:&nbsp;&nbsp;</strong><br /> 
  <%= @family.phone %><br /><br />

<strong>Active?&nbsp;&nbsp;</strong>
  <%= @family.active ? "Yes" : "No" %><br /><br />


<%= link_to "Family Report", family_report_path(id: @family), class: "button tiny radius" %>&nbsp;&nbsp;
<%= link_to "Edit this family", edit_family_path(@family), class: "button tiny radius" %>&nbsp;&nbsp;
<%= link_to 'Destroy family', family_path(@family), data: { confirm: 'Are you sure you want to permanently remove this family from the system?' }, method: :delete, class: "button tiny radius alert" %>

app/views/families/_family_students.html.erb
<% unless @students.empty? %>
  <!-- <h3>&nbsp;</h3> -->
  <div class="panel clearfix">
    <h5>Students:</h5>
    <ul class="side-nav">
      <% @students.each do |student| %>
        <li><%= link_to "#{student.name}", student_path(student) %></li>
      <% end %>
    </ul>
  </div>

<% else %>
  <div class="panel clearfix">
    <h5>CStudent has not been used</h5>
  </div>
<% end %>

app/views/families/_form.html.erb
<%= simple_form_for(@family, html: { class: 'form-horizontal' }) do |f| %>
   
   <h3><%= controller.action_name.capitalize %> Family</h3>
    
    <%= f.input :family_name %>
    <%= f.input :parent_first_name %>
    <%= f.input :phone %>
    <%= f.input :email %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, class: 'button radius' %>
      <%= link_to 'Back to list of families', families_path, :class => 'button secondary radius' %>
    </div>

<% end %>

app/views/families/_inactive_families.html.erb
<% unless @inactive_families.empty? %>
  <div class="panel clearfix">
    <h5>Inactive Families</h5>
    <ul class="side-nav">
      <% @inactive_families.each do |family| %>
        <li><%= link_to family.family_name, family_path(family) %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/families/index.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "active_families" %>
    <br />
    <%= link_to "Add a new family", new_family_path, class: "button tiny radius" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'inactive_families' %>
  </div>
</div>

app/views/families/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- MAIN CONTENT GOES HERE -->
    <%= render :partial => "family_details" %>
  </div>

  <div class="small-1 columns">
    &nbsp;
  </div>

  <div class="small-4 columns">
    <!-- SIDEBAR CONTENT GOES HERE -->
    <%= render partial: 'family_students' %>
  </div>
</div>