config/routes.rb
ChessCamp::Application.routes.draw do
  resources :reports

  get "students/edit"
  get "students/index"
  get "students/new"
  get "students/show"
  get "families/edit"
  get "families/index"
  get "families/new"
  get "families/show"
  get "locations/edit"
  get "locations/new"
  get "locations/index"
  get "locations/show"
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps 
  resources :users
  resources :sessions
  resources :locations
  resources :families
  resources :students
  # semi-static routes
  get 'report/year/:year', to: 'report#yearly', as: :yearly
  get 'report/:id', to: 'report#generate', as: :helper
  get 'report/family/:id', to: 'report#family_report', as: :family_report
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/payment_report', to: 'home#payment_report', as: :payment_report
  get 'home/payment_report13', to: 'home#payment_report13', as: :payment_report13
  get 'home/payment_report15', to: 'home#payment_report15', as: :payment_report15
  #get 'home/payment_report/:year', to: 'home#payment_report', as: :payment_report
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # set the root url
  root to: 'home#index'

end

app/views/partials/_footer.html.erb
<p class="supertiny">&nbsp;</p>

  <%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About Us', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'Privacy Policy', privacy_path %>
  <br /><br />
  <div id="copy">
    Webmaster: <%= mail_to("annieche@andrew.cmu.edu", "Annie Chen", encode: "javascript") %> 
    &nbsp;&nbsp;&copy 2014
  </div>

app/views/partials/_nav.html.erb
  <div class="contain-to-grid">
    <nav class="top-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
          <%= link_to image_tag('amcc_logo.png'), home_path %>
        </li>
      </ul>
      <section class="top-bar-section">
        <ul class="left">
          <% if logged_in? %>
            <% if current_user.role == 'admin' %>
          <!-- options for curriculums -->
          <li class="has-dropdown">
            <%= link_to "Curriculums", curriculums_path %>
            <ul class="dropdown">
              <li><%= link_to "List Curriculums", curriculums_path %></li>
              <li><%= link_to "Add a Curriculum", new_curriculum_path %></li>
            </ul>
          </li>

          <!-- options for camps -->
          <li class="has-dropdown">
            <%= link_to "Camps", camps_path %>
            <ul class="dropdown">
              <li><%= link_to "List Camps", camps_path %></li>
              <li><%= link_to "Add a Camp", new_camp_path %></li>
            </ul>
          </li>

          <!-- options for instructors -->
          <li class="has-dropdown">
            <%= link_to "Instructors", instructors_path %>
            <ul class="dropdown">
              <li><%= link_to "List Instructors", instructors_path %></li>
              <li><%= link_to "Add an Instructor", new_instructor_path %></li>
            </ul>
          </li>

          <li class="has-dropdown">
            <%= link_to "Locations", locations_path %>
            <ul class="dropdown">
              <li><%= link_to "List Locations", locations_path %></li>
              <li><%= link_to "Add a Location", new_location_path %></li>
            </ul>
          </li>

          <li class="has-dropdown">
            <%= link_to "Families", families_path %>
            <ul class="dropdown">
              <li><%= link_to "List Families", families_path %></li>
              <li><%= link_to "Add a Family", new_family_path %></li>
            </ul>
          </li>

          <li class="has-dropdown">
            <%= link_to "Students", students_path %>
            <ul class="dropdown">
              <li><%= link_to "List Students", students_path %></li>
              <li><%= link_to "Add a Student", new_student_path %></li>
            </ul>
          </li>
            <% else %>

            <li class="has-dropdown">
              <%= link_to "Curriculums", curriculums_path %>
              <ul class="dropdown">
                <li><%= link_to "List Curriculums", curriculums_path %></li>
                <li><%= link_to "Add a Curriculum", new_curriculum_path %></li>
              </ul>
            </li>
            <li class="has-dropdown">
              <%= link_to "Camps", camps_path %>
              <ul class="dropdown">
                <li><%= link_to "List Camps", camps_path %></li>
              </ul>
            </li>
            
            <li class="has-dropdown">
            <%= link_to "Students", students_path %>
            <ul class="dropdown">
              <li><%= link_to "List Students", students_path %></li>
            </ul>
          </li>
          <% end %>
          <% else %>
            <li class="has-dropdown">
              <%= link_to "Curriculums", curriculums_path %>
              <ul class="dropdown">
                <li><%= link_to "List Curriculums", curriculums_path %></li>
              </ul>
            </li>
            <li class="has-dropdown">
              <%= link_to "Camps", camps_path %>
              <ul class="dropdown">
                <li><%= link_to "List Camps", camps_path %></li>
              </ul>
            </li>
          <% end %>

          </li>
        </ul>
      </section>
    </nav>
  </div>