config/routes.rb
ChessCamp::Application.routes.draw do
  resources :reports

  get "students/edit"
  get "students/index"
  get "students/new"
  get "students/show"
  get "families/edit"
  get "families/index"
  get "families/new"
  get "families/show"
  get "locations/edit"
  get "locations/new"
  get "locations/index"
  get "locations/show"
  # generated routes
  resources :curriculums
  resources :instructors
  resources :camps 
  resources :users
  resources :sessions
  resources :locations
  resources :families
  resources :students
  # semi-static routes
  get 'report/year/:year', to: 'report#yearly', as: :yearly
  get 'report/:id', to: 'report#generate', as: :helper
  get 'report/family/:id', to: 'report#family_report', as: :family_report
  get 'home', to: 'home#index', as: :home
  get 'home/about', to: 'home#about', as: :about
  get 'home/contact', to: 'home#contact', as: :contact
  get 'home/privacy', to: 'home#privacy', as: :privacy
  get 'home/payment_report', to: 'home#payment_report', as: :payment_report
  get 'home/payment_report13', to: 'home#payment_report13', as: :payment_report13
  get 'home/payment_report15', to: 'home#payment_report15', as: :payment_report15
  #get 'home/payment_report/:year', to: 'home#payment_report', as: :payment_report
  get 'user/edit' => 'users#edit', :as => :edit_current_user
  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # set the root url
  root to: 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  require 'will_paginate/array'

  def payment_report
    @activeCamps = Camp.active.chronological
    @y14 = @activeCamps.select{|c| c.start_date.year==2014}
  end

  def payment_report13
    @activeCamps = Camp.active.chronological
    @y13 = @activeCamps.select{|c| c.start_date.year==2013}
  end 

  def payment_report15
    @activeCamps = Camp.active.chronological
    @y15 = @activeCamps.select{|c| c.start_date.year==2015}
  end

  def index
  	@activeCamps = Camp.active.chronological
    @camps = Camp.upcoming.active.chronological.paginate(:page => params[:page]).per_page(10)
    @y14 = @activeCamps.select{|c| c.start_date.year==2014}
    @y13 = @activeCamps.select{|c| c.start_date.year==2013}
    @y15 = @activeCamps.select{|c| c.start_date.year==2015}


    if current_user && !current_user.instructor.nil?
      @userCamps = current_user.instructor.camps
      @possible_to_see_upcoming_camps = @userCamps.select{|c| (can? :read, c)}.paginate(:page => params[:page], :per_page => 10)
      @userCamps = @possible_to_see_upcoming_camps

      @userInstructor = current_user.instructor
    end
  	# usercamps = current_user.instructor.camps.map{|c| c }.flatten
  	# @ucamps = usercamps.upcoming.active.chronological.paginate(:page => params[:page]).per_page(10)
  end

  def show
  	@activeCamps = Camp.active.chronological
    @camps = Camp.upcoming.active.chronological.paginate(:page => params[:page]).per_page(10)
    @y14 = @activeCamps.select{|c| c.start_date.year==2014}
    @y13 = @activeCamps.select{|c| c.start_date.year==2013}
  	# @usercamps = current_user.instructor.camps.upcoming.active.chronological.paginate(:page => params[:page]).per_page(10)
  	#@instructors = @camp.instructors.alphabetical.to_a
  end

  def about
  end

  def contact
  end

  def privacy
  end

end

app/views/home/_admin_camp.html.erb
<table class="table">
  <tr>
    <th width="260">Name</th>
    <th width="120">Start On</th>
    <th width="120">Registrations</th>
    <th width="120">Instructors</th>
    <th></th>
    <th></th>
  </tr>

<% @userCamps.each do |camp| %>
  <tr>
    <td><%= link_to camp.name, camp_path(camp) %></td>
    <td align="center"><%= camp.start_date.strftime('%m/%d/%y') %></td>
    <td align="center"><%= camp.registrations.size %></td>
    <td align="center">
      <% camp.instructors.each do |i| %>
      <%= link_to i.name, instructor_path(i) %><br />
      <% end %> </td>
    <td><% if current_user.role == 'admin' %>
      <%= link_to 'Edit  ', edit_camp_path(camp), class: "button tiny radius" %>
        <%end%></td>
    <td>
        <% if current_user.role == 'admin' %>
        <%= link_to 'Report', helper_path(camp), class: "button tiny radius" %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>
<!-- Add the pagination using will_paginate gem -->
<span class="paginate">
<%= will_paginate @camps, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" %>
</span>

app/views/home/_admin_home.html.erb
<!-- An administrator user who logs in is immediately taken to his/her 
dashboard where they can see key information about camp registrations 
and instructor assignments. It is left as an exercise to the student 
developer to determine what information makes the most sense to 
include on this dashboard and how to display it.  -->

<h3>Welcome back, <%if current_user.instructor.nil?%> <%= current_user.username %> <% else%> 
	<%=current_user.instructor.first_name %><%end%></h3>

<p>Below are information on camp registrations and instructor assignments:</p>

<table border="0" cellspacing="5" cellpadding="5">
	<tr valign="top">
		<td>
			<h3>Your Upcoming Camps &nbsp;&nbsp;</h3>
			<% if @userCamps.nil? || @userCamps.empty? %>
				<p>There are no camps at this time</p>
			<% else %>
				<div id="display_camps">
					<%= render :partial => "admin_camp" %>
				</div>
			<% end %>
		</td>
		<td width="100">&nbsp;</td>
		
		<td>
			<div class="panel clearfix">
			<h3><span id="task_title">Yearly Reports</span>  &nbsp;&nbsp;</h3>
			<%= link_to 'Payment Report 2013', yearly_path(year: "2013") %> <br />
			<%= link_to 'Payment Report 2014', yearly_path(year: "2014") %> <br />
			<%= link_to 'Payment Report 2015', yearly_path(year: "2015") %> <br />

			<!-- For a given camp, list of all payments received and balances due along with 
grand totals for each. 
 
2. List of all payments received and balances due for a particular family for a 
particular year. -->
		</div>
		</td>
	</tr>
</table>

app/views/home/_instr_home.html.erb
<!-- An instructor user who logs in is immediately taken to his/her dashboard 
where they can see their personal information and as well as upcoming 
camps they are assigned to. The exact details of this dashboard content 
and layout is left to the student developer to decide.  -->

<h3>Welcome back, Instructor <%= @userInstructor.proper_name %></h3>

<p>Below is information on your projects and incomplete tasks for those projects:</p>

<table border="0" cellspacing="5" cellpadding="5">
	<tr valign="top">
		<td>
			<h3>Upcoming Camp Information &nbsp;&nbsp;</h3>
			<% if @userCamps.nil? || @userCamps.empty? %>
				<p>There are no camps at this time</p>
			<% else %>
				<div id="display_camps">
					<%= render :partial => "admin_camp" %>
				</div>
			<% end %>
		</td>
		<td width="100">&nbsp;</td>
		<td>
			<h3><span id="task_title">Your Profile</span>  &nbsp;&nbsp;</h3>
			<% unless @userInstructor.picture_url.nil? %>
			    <p><%= image_tag @userInstructor.picture_url %></p>
			<% end %>
			<strong>Name:&nbsp;&nbsp;</strong> 
			  <%= @userInstructor.proper_name %><br /><br />
			<strong>Username:&nbsp;&nbsp;</strong>
			<%= current_user.username %><br /><br />
			<strong>Phone:&nbsp;&nbsp;</strong> 
			  <%= number_to_phone(@userInstructor.phone) %><br /><br />
			<strong>Email:&nbsp;&nbsp;</strong> 
			  <%= mail_to @userInstructor.email, @userInstructor.email, encode: "javascript" %><br /><br />
			<strong>Biography</strong><br />
  				<%= @userInstructor.bio.nil? ? "N/A" : @userInstructor.bio %><br /><br />
			<%= link_to "Edit Profile", edit_instructor_path(@userInstructor), class: "button tiny radius" %>&nbsp;&nbsp;
		</td>
	</tr>
</table>

app/views/home/about.html.erb
<div class = "transparent">
<h2>About the A &amp; M Chess Camps</h2>

<%= image_tag 'BoysPlaying2.jpg' %>
<p class="supertiny">&nbsp;</p>
<p> 
  This is a fictional chess camp created for the Spring '14 67-272 Project. 
</p>
</div>

app/views/home/contact.html.erb
<div class = "transparent">
<h2>Contact A &amp; M Chess Camps</h2>

<p> <%= image_tag 'Kelsey1.jpg', class: "left", width: 150 %>If you have any questions and concerns, please contact us at: </p>

<table cellpadding="3" class="table">
  <tr>
    <td>Webmaster:&nbsp;&nbsp;&nbsp;</td>
    <td>Annie Chen</td>
  </tr>
  <tr>
    <td>Email:</td>
    <td>
    <%= mail_to("annieche@andrew.cmu.edu", "Annie", encode: "javascript") %> 
    </td>
  </tr>
  <tr>
    <td>Phone:</td>
    <td>909-912-9987</td>
  </tr>
</table>
</div>

app/views/home/index.html.erb
<div class = "transparent">
<% if logged_in? %>
	<% if current_user.role == 'admin' %>
		<%= render :partial => 'admin_home' %>
	<% else %>
		<%= render :partial => 'instr_home'%>
	<% end %>
<% else %>
	<h2>Welcome Chess Parents!</h2>

	<p><%= image_tag 'AlexPlaying10.jpg', class: "left", width: "150" %> The A &amp; M 
	  Chess Camps are the finest chess camps in the United States (<em>we concede 
	  Russia can do better, but not much better</em>) and guaranteed to 
	  <strong>transform your son or daughter into a tiger at the chess board</strong>.  
	  The navigation bar above will tell you more about our camps, curriculums and 
	  instructors and in the future will actually allow you to register your son 
	  or daughter for those camps.
	</p>

	<!-- <p>If you are an administrator (don't lie), <%= link_to "click here to review camps.", camps_path %></p> -->
<% end %>
</div>

app/views/home/privacy.html.erb
<div class = "transparent">
<h2>The A &amp; Privacy Policy</h2>

<p>Your privacy is important to us, and maintaining your trust and confidence is one of our highest priorities. We respect your right to keep your personal information confidential and understand your desire to avoid unwanted solicitations. 
</p>
</div>